version: '3.8'

services:
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./.next:/app/.next
    restart: unless-stopped

networks:
  default:
    driver: bridge